#!/usr/bin/expect
set AR_IP [lindex $argv 0]
spawn telnet 192.168.1.1
expect "#" {
puts "ARIP is $AR_IP"
if { $AR_IP != "192.168.1.2"} {
    send "iptables -A INPUT -s 192.168.1.2 -j DROP\r";
    sleep 0.5;
}

if { $AR_IP != "192.168.1.3"} {
    send "iptables -A INPUT -s 192.168.1.3 -j DROP\r";
    sleep 0.5;
}

if { $AR_IP != "192.168.1.4"} {
    send "iptables -A INPUT -s 192.168.1.4 -j DROP\r";
    sleep 0.5;
}

if { $AR_IP != "192.168.1.5"} {
    send "iptables -A INPUT -s 192.168.1.5 -j DROP\r";
    sleep 0.5;
}

if { $AR_IP != "192.168.1.6"} {
    send "iptables -A INPUT -s 192.168.1.6 -j DROP\r";
    sleep 0.5;
}
send "exit \r"
}

interact
